---
# tasks file for Install_Google_Chrome
- name: Include Fedora/RHEL tasks 
  include_tasks: fedora.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Include Fedora/RHEL tasks 
  include_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'
