---
# tasks file for Update_OS
- name: Update OS | RHEL and derivatives
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Update OS | Debian and derivatives
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
