---
- hosts: all
  gather_facts: true
  connection: local

- include: ../vars/debian.yaml
  when: ansible_distribution == "Ubuntu"
  tags: package

- include: ../vars/redhat.yaml
  when: ansible_distribution == "Fedora" or ansible_distribution == "Red Hat" or ansible_distribution == "CentOS"
  tags: package

- name: Manage Users 
  gather_facts: no
  tasks:
    - name: Add User 'James Radtke'
      ansible.builtin.user:
      name: jradtke
      comment: James Radtke
      shell: /bin/bash
      uid: 2025
      groups: '{{ admin_groups }}'
    - name: Add User 'Mamie Colburn'
      ansible.builtin.user:
      name: mcolburn 
      comment: Mamie Colburn
      shell: /bin/bash
      uid: 2026
