---
- name: Manage Users | grab OS-based vars
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Add User | James Radtke
      ansible.builtin.user:
        name: jradtke
        comment: James Radtke
        shell: /bin/bash
        uid: 2025
        groups: "{{ admin_groups }}"
    - name: Add User | M C
      ansible.builtin.user:
        name: mcolburn
        comment: M C
        shell: /bin/bash
        uid: 2026
    
    - include_vars: "{{ admin_groups, standard_groups }}"
      with_first_found:
        - ../vars/"{{ ansible_distribution }}.yaml"
      tags: vars

