---
- name: Manage Users - OS-based vars
  include: ../vars/debian.yaml
    when: ansible_distribution == "Ubuntu"
    tags: package

  include: ../vars/redhat.yaml
    when: ansible_distribution == "Fedora" or ansible_distribution == "Red Hat" or ansible_distribution == "CentOS"
    tags: package


- hosts: all
  gather_facts: true

  tasks:
    - name: Add User 'James Radtke'
      ansible.builtin.user:
      name: jradtke
      comment: James Radtke
      shell: /bin/bash
      uid: 2025
      groups: '{{ admin_groups }}'
    - name: Add User 'Mamie Colburn'
      ansible.builtin.user:
      name: mcolburn
      comment: Mamie Colburn
      shell: /bin/bash
      uid: 2026

